project_id = "jqynxytwngtytvuzucuo"

[functions.receive-email]
verify_jwt = false

[functions.send-member-invitation]
verify_jwt = true

[functions.send-company-invitation]
verify_jwt = true

[functions.send-password-reset]
verify_jwt = false

[functions.send-password-otp]
verify_jwt = false

[functions.verify-password-otp]
verify_jwt = false